#!/bin/bash
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

exec 1>&2

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

missing_license=0

IFS='
'
for FILE in $(git diff --cached --name-only $against); do
  # Ignore binary files.
  ( file --mime "$FILE" | grep charset=binary >/dev/null ) && continue
  # Ignore third_party.
  [[ "$FILE" = *third_party* ]] && continue
  # Ignore markdown
  [[ "$FILE" = *.md ]] && continue

  # Find files with trailing whitespace
  if grep -E '\s+$' "$FILE"; then
    echo -n "Fixing whitespace in $FILE"
  fi
  # Fix up trailing white-space & extra lines at EOF.
  sed -i '' 's/[  ]*$//' "$FILE" && \
      sed -i '' -e ':a' -e '/^\n*$/{$d;N;ba' -e '}' "$FILE" && \
      git add "$FILE"

  # Ignore assets for license header.
  [[ "$FILE" = *assets/* ]] && continue
  # Check for missing license header.
  [[ "$FILE" = *third_party* ]] && continue
  echo checking $FILE
  if ! head "$FILE" | grep 'The Chromium Authors' > /dev/null; then
    missing_license=1
    echo "Missing license header: $FILE"
  fi
done

exit $missing_license
